package cn.edu.bjtu.brilley.domain;

public class Chats {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chats.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chats.sessionId
     *
     * @mbggenerated
     */
    private String sessionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chats.senderId
     *
     * @mbggenerated
     */
    private Integer senderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chats.receiverId
     *
     * @mbggenerated
     */
    private Integer receiverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chats.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chats.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chats.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chats.updatedAt
     *
     * @mbggenerated
     */
    private String updatedat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chats.others
     *
     * @mbggenerated
     */
    private String others;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chats.id
     *
     * @return the value of chats.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chats.id
     *
     * @param id the value for chats.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chats.sessionId
     *
     * @return the value of chats.sessionId
     *
     * @mbggenerated
     */
    public String getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chats.sessionId
     *
     * @param sessionid the value for chats.sessionId
     *
     * @mbggenerated
     */
    public void setSessionid(String sessionid) {
        this.sessionid = sessionid == null ? null : sessionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chats.senderId
     *
     * @return the value of chats.senderId
     *
     * @mbggenerated
     */
    public Integer getSenderid() {
        return senderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chats.senderId
     *
     * @param senderid the value for chats.senderId
     *
     * @mbggenerated
     */
    public void setSenderid(Integer senderid) {
        this.senderid = senderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chats.receiverId
     *
     * @return the value of chats.receiverId
     *
     * @mbggenerated
     */
    public Integer getReceiverid() {
        return receiverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chats.receiverId
     *
     * @param receiverid the value for chats.receiverId
     *
     * @mbggenerated
     */
    public void setReceiverid(Integer receiverid) {
        this.receiverid = receiverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chats.content
     *
     * @return the value of chats.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chats.content
     *
     * @param content the value for chats.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chats.type
     *
     * @return the value of chats.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chats.type
     *
     * @param type the value for chats.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chats.sort
     *
     * @return the value of chats.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chats.sort
     *
     * @param sort the value for chats.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chats.updatedAt
     *
     * @return the value of chats.updatedAt
     *
     * @mbggenerated
     */
    public String getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chats.updatedAt
     *
     * @param updatedat the value for chats.updatedAt
     *
     * @mbggenerated
     */
    public void setUpdatedat(String updatedat) {
        this.updatedat = updatedat == null ? null : updatedat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chats.others
     *
     * @return the value of chats.others
     *
     * @mbggenerated
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chats.others
     *
     * @param others the value for chats.others
     *
     * @mbggenerated
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }
}