package cn.edu.bjtu.brilley.domain;

public class Emoticons {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emoticons.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emoticons.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emoticons.src
     *
     * @mbggenerated
     */
    private String src;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emoticons.createdAt
     *
     * @mbggenerated
     */
    private String createdat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emoticons.id
     *
     * @return the value of emoticons.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emoticons.id
     *
     * @param id the value for emoticons.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emoticons.userId
     *
     * @return the value of emoticons.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emoticons.userId
     *
     * @param userid the value for emoticons.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emoticons.src
     *
     * @return the value of emoticons.src
     *
     * @mbggenerated
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emoticons.src
     *
     * @param src the value for emoticons.src
     *
     * @mbggenerated
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emoticons.createdAt
     *
     * @return the value of emoticons.createdAt
     *
     * @mbggenerated
     */
    public String getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emoticons.createdAt
     *
     * @param createdat the value for emoticons.createdAt
     *
     * @mbggenerated
     */
    public void setCreatedat(String createdat) {
        this.createdat = createdat == null ? null : createdat.trim();
    }
}