package cn.edu.bjtu.brilley.domain;

public class Sessions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessions.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessions.sessionId
     *
     * @mbggenerated
     */
    private String sessionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessions.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessions.receiverId
     *
     * @mbggenerated
     */
    private Integer receiverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessions.lastChat
     *
     * @mbggenerated
     */
    private String lastchat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessions.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessions.read
     *
     * @mbggenerated
     */
    private Integer read;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessions.updatedAt
     *
     * @mbggenerated
     */
    private String updatedat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessions.id
     *
     * @return the value of sessions.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessions.id
     *
     * @param id the value for sessions.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessions.sessionId
     *
     * @return the value of sessions.sessionId
     *
     * @mbggenerated
     */
    public String getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessions.sessionId
     *
     * @param sessionid the value for sessions.sessionId
     *
     * @mbggenerated
     */
    public void setSessionid(String sessionid) {
        this.sessionid = sessionid == null ? null : sessionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessions.userId
     *
     * @return the value of sessions.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessions.userId
     *
     * @param userid the value for sessions.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessions.receiverId
     *
     * @return the value of sessions.receiverId
     *
     * @mbggenerated
     */
    public Integer getReceiverid() {
        return receiverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessions.receiverId
     *
     * @param receiverid the value for sessions.receiverId
     *
     * @mbggenerated
     */
    public void setReceiverid(Integer receiverid) {
        this.receiverid = receiverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessions.lastChat
     *
     * @return the value of sessions.lastChat
     *
     * @mbggenerated
     */
    public String getLastchat() {
        return lastchat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessions.lastChat
     *
     * @param lastchat the value for sessions.lastChat
     *
     * @mbggenerated
     */
    public void setLastchat(String lastchat) {
        this.lastchat = lastchat == null ? null : lastchat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessions.type
     *
     * @return the value of sessions.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessions.type
     *
     * @param type the value for sessions.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessions.read
     *
     * @return the value of sessions.read
     *
     * @mbggenerated
     */
    public Integer getRead() {
        return read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessions.read
     *
     * @param read the value for sessions.read
     *
     * @mbggenerated
     */
    public void setRead(Integer read) {
        this.read = read;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessions.updatedAt
     *
     * @return the value of sessions.updatedAt
     *
     * @mbggenerated
     */
    public String getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessions.updatedAt
     *
     * @param updatedat the value for sessions.updatedAt
     *
     * @mbggenerated
     */
    public void setUpdatedat(String updatedat) {
        this.updatedat = updatedat == null ? null : updatedat.trim();
    }
}