package cn.edu.bjtu.brilley.dao;

import cn.edu.bjtu.brilley.domain.Chats;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ChatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chats
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chats
     *
     * @mbggenerated
     */
    int insert(Chats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chats
     *
     * @mbggenerated
     */
    int insertSelective(Chats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chats
     *
     * @mbggenerated
     */
    Chats selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chats
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Chats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chats
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Chats record);

    List<Chats> getChatList(String sessionId, String lastTime);
}