package cn.edu.bjtu.brilley.dao;

import cn.edu.bjtu.brilley.domain.Emoticons;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface EmoticonsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emoticons
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emoticons
     *
     * @mbggenerated
     */
    int insert(Emoticons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emoticons
     *
     * @mbggenerated
     */
    int insertSelective(Emoticons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emoticons
     *
     * @mbggenerated
     */
    Emoticons selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emoticons
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Emoticons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emoticons
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Emoticons record);

    List<Emoticons> getEmoticonList(Integer userId);

    int addEmoticon(Emoticons emoticons);
}