package cn.edu.bjtu.brilley.dao;

import cn.edu.bjtu.brilley.domain.Files;
import cn.edu.bjtu.brilley.domain.Friends;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface FilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated
     */
    int insert(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated
     */
    int insertSelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated
     */
    Files selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Files record);

}