package cn.edu.bjtu.brilley.dao;

import cn.edu.bjtu.brilley.domain.Friends;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface FriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    int insert(Friends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    int insertSelective(Friends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    Friends selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Friends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friends
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Friends record);



    int getIsFriend(Integer userId, Integer friendId);

    int addFriend(Friends friends);

    int deleteFriend(Integer userId, Integer friendId);

    List<Friends> getFriendList(Integer userId);

    List<Friends> getFriendInfoById(Integer userId, Integer friendId);

}