package cn.edu.bjtu.brilley.dao;

import cn.edu.bjtu.brilley.domain.FriendRequests;

public interface FriendRequestsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_requests
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_requests
     *
     * @mbggenerated
     */
    int insert(FriendRequests record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_requests
     *
     * @mbggenerated
     */
    int insertSelective(FriendRequests record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_requests
     *
     * @mbggenerated
     */
    FriendRequests selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_requests
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FriendRequests record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_requests
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FriendRequests record);
}