package cn.edu.bjtu.brilley.dao;

import cn.edu.bjtu.brilley.domain.FriendRequests;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface FriendRequestsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_requests
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_requests
     *
     * @mbggenerated
     */
    int insert(FriendRequests record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_requests
     *
     * @mbggenerated
     */
    int insertSelective(FriendRequests record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_requests
     *
     * @mbggenerated
     */
    FriendRequests selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_requests
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FriendRequests record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_requests
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FriendRequests record);

    /**
     * new created
     * @param record
     * @return
     */
    int addFriendRequest(FriendRequests record);

    int isExistFriendRequest(Integer userId, Integer friendId);

    int updateFriendRequest(FriendRequests record);

    List<FriendRequests> getFriendRequestList(Integer userId, String lastTime);

    List<FriendRequests> getFriendRequestById(Integer requestId);

}