package cn.edu.bjtu.brilley.dao;

import cn.edu.bjtu.brilley.domain.ListSong;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ListSongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbggenerated
     */
    int insert(ListSong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbggenerated
     */
    int insertSelective(ListSong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbggenerated
     */
    ListSong selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ListSong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbggenerated
     */


    int updateListSongMsg(ListSong record);

    int deleteListSong(Integer songId);

    List<ListSong> allListSong();

    List<ListSong> listSongOfSongId(Integer songListId);
}