package cn.edu.bjtu.brilley.dao;

import cn.edu.bjtu.brilley.domain.Notifications;

public interface NotificationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbggenerated
     */
    int insert(Notifications record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbggenerated
     */
    int insertSelective(Notifications record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbggenerated
     */
    Notifications selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Notifications record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Notifications record);
}