package cn.edu.bjtu.brilley.dao;

import cn.edu.bjtu.brilley.domain.RankList;

public interface RankListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank_list
     *
     * @mbggenerated
     */
    int insert(RankList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank_list
     *
     * @mbggenerated
     */
    int insertSelective(RankList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank_list
     *
     * @mbggenerated
     */
    RankList selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RankList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RankList record);
}