package cn.edu.bjtu.brilley.dao;

import cn.edu.bjtu.brilley.domain.Sessions;

public interface SessionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    int insert(Sessions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    int insertSelective(Sessions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    Sessions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sessions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sessions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sessions record);
}